---
- hosts: localhost
  connection: local
  vars_files:
    - vars.yml
  gather_facts: false
  tasks:

# WebGoat normal content check
    - name: Check that a page returns what it should
      uri:
        url: '{{ item.vsip }}{{ item."
        return_content: true
      register: request
      until: "'Register new user' in request.content"
      retries: 15
      delay: 10
